- hosts: all
  tasks:
          - name: Creating a Docker Repository
            yum_repository:
                 description: repo for docker
                 name: "docker-ce"
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                 gpgcheck: "no"
                
          - name: Installing Docker
            package:
                    name: "docker-ce-18.09.1-3.el7.x86_64"
                    state: present

          
          - name: Starting Docker Service
            service:
                   name: docker
                   state: started
                   enabled: yes
          - pip: 
                name: docker-py

          - name: Pulling Docker Image
            docker_image:
                   name: httpd
                   tag: "latest"
                   source: pull
          
          - name: Creating a Directory in Controller Node
            file:
                 path: /root/project
                 state: directory

          - name: Launch a Docker Container
            docker_container:
                      name: myweb
                      image: httpd 
                      ports:
                          -  "82:80"
                      state: started
                      detach: yes
                      volumes: /root/project:/usr/local/apache2/htdocs/
              
          - name: Deploy a folder in the same document root
            copy:
                    dest: /root/project/web.html
                    content: <h1>Web Page Is Running Successfully ...<h2>
  

